=== jumpinjackie/mapguide-react-layout/fusion/docs/ApplicationDefinition-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="ApplicationDefinition" type="ApplicationDefinitionType" />
  <xs:complexType name="ApplicationDefinitionType">
    <xs:sequence>
      <xs:element name="Title" type="xs:string" minOccurs="0" />
      <xs:element name="TemplateUrl" type="xs:string" minOccurs="0" />
      <xs:element name="MapSet" type="MapSetType" minOccurs="0" maxOccurs="1" />
      <xs:element name="WidgetSet" type="WidgetSetType" minOccurs="1" maxOccurs="unbounded" />
      <xs:element name="Extension" type="CustomContentType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CustomContentType">
    <xs:sequence>
      <xs:any processContents="lax"   minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MapSetType">
    <xs:sequence>
      <xs:element name="MapGroup" type="MapGroupType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MapGroupType">
    <xs:sequence>
      <xs:element name="InitialView" type="MapViewType" minOccurs="0"/>
      <xs:element name="Map" type="MapType" minOccurs="1" maxOccurs="unbounded" />
      <xs:element name="Extension" type="CustomContentType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="MapViewType">
    <xs:sequence>
      <xs:element name="CenterX" type="xs:double"/>
      <xs:element name="CenterY" type="xs:double"/>
      <xs:element name="Scale" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>  
  <xs:complexType name="MapType">
    <xs:sequence>
      <xs:element name="Type" type="xs:string" />
      <xs:element name="SingleTile" type="xs:string" minOccurs="0" />
      <xs:element name="Extension" type="CustomContentType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="WidgetSetType">
    <xs:sequence>
      <xs:element name="Container" type="ContainerType" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="MapWidget" type="MapWidgetType" />
      <xs:element name="Widget" type="WidgetType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="WidgetType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Type" type="xs:string" />
      <xs:element name="Location" type="xs:string" minOccurs="0"/>
      <xs:element name="Extension" type="CustomContentType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MapWidgetType">
    <xs:complexContent>
      <xs:extension base="WidgetType">
        <xs:sequence>
          <xs:element name="MapId" type="xs:string" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UiWidgetType">
    <xs:complexContent>
      <xs:extension base="WidgetType">
        <xs:sequence>
          <xs:element name="ImageUrl" type="xs:string" />
          <xs:element name="ImageClass" type="xs:string" />
          <xs:element name="Label" type="xs:string" />
          <xs:element name="Tooltip" type="xs:string" />
          <xs:element name="StatusText" type="xs:string" />
          <xs:element name="Disabled" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ContainerType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Type" type="xs:string" />
      <xs:element name="Position" type="xs:string" />
      <xs:element name="Extension" type="CustomContentType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UiItemContainerType">
    <xs:complexContent>
      <xs:extension base="ContainerType">
        <xs:sequence>
          <xs:element name="Item" type="UiItemType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="UiItemType" abstract="true">
    <xs:sequence>
      <xs:element name="Function" type="UiItemFunctionType" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="UiItemFunctionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Separator" />
      <xs:enumeration value="Widget" />
      <xs:enumeration value="Flyout" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="FlyoutItemType">
    <xs:complexContent>
      <xs:extension base="UiItemType">
        <xs:sequence>
          <xs:element name="Label" type="xs:string" />
          <xs:element name="Tooltip" type="xs:string" minOccurs="0" />
          <xs:element name="ImageUrl" type="xs:string" minOccurs="0" />
          <xs:element name="ImageClass" type="xs:string" minOccurs="0"/>
          <xs:element name="Item" type="UiItemType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="SeparatorItemType">
    <xs:complexContent>
      <xs:extension base="UiItemType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="WidgetItemType">
    <xs:complexContent>
      <xs:extension base="UiItemType">
        <xs:sequence>
          <xs:element name="Widget" type="xs:string" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== jumpinjackie/mapguide-react-layout/fusion/docs/tutorial/fullPage/ApplicationDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<ApplicationDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="ApplicationDefinition-1.0.0.xsd">

<!-- ****************************************** 
* MapSet
* 
* Contains the map(s) you want available to your
* application.
 ****************************************** -->

  <MapSet>
    <MapGroup id="sheboygan">
      <Map>
        <Type>MapGuide</Type>
        <SingleTile>true</SingleTile>
        <Extension>
          <ResourceId>Library://Samples/Sheboygan/Maps/Sheboygan.MapDefinition</ResourceId>
          <ImageFormat>PNG8</ImageFormat>
          <SelectionAsOverlay>true</SelectionAsOverlay>
          <SelectionFormat>PNG</SelectionFormat>
          <SelectionColor>0xFF0000FF</SelectionColor>
          <ProjectionCode>EPSG:4326</ProjectionCode>
        </Extension>
      </Map>
    </MapGroup>
    <MapGroup id="mixed">
      <Map>
        <Type>WMS</Type>
        <Extension>
          <ResourceId>http://localhost/cgi-bin/testwms.exe</ResourceId>
          <Options>
            <name>test WMS</name>
            <singleTile>true</singleTile>
            <!--maxResolution>auto</maxResolution>
            <minScale>1000000000</minScale-->
          </Options>
          <Parameters>
            <layers>bathymetry</layers>
            <transparent>true</transparent>
          </Parameters>
        </Extension>
      </Map>
      <Map>
        <Type>MapGuide</Type>
        <SingleTile>true</SingleTile>
        <Extension>
          <ResourceId>Library://Samples/Sheboygan/Maps/Sheboygan.MapDefinition</ResourceId>
          <SelectionAsOverlay>true</SelectionAsOverlay>
          <SelectionFormat>PNG</SelectionFormat>
          <SelectionColor>0xFF0000FF</SelectionColor>
        </Extension>
      </Map>
    </MapGroup>
  </MapSet>

<!-- ****************************************** 
* WidgetSet
*
* Contains the widgets you want available to your 
* application.
 ****************************************** -->

  <WidgetSet>

<!-- ****************************************** 
* ContextMenu (Map)
*
* Menu available to the Map on right-click
 ****************************************** -->

    <Container>
      <Name>MapContextMenu</Name>
      <Type>ContextMenu</Type>
      <Item>
        <Function>Widget</Function>
        <Widget>menuPan</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>menuZoomInRectangle</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>menuZoomInFixed</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>menuZoomOutFixed</Widget>
      </Item>
    </Container>

<!-- ****************************************** 
* Toolbar (Primary)
*
* 
 ****************************************** -->

    <Container>
      <Name>navigationToolbar</Name>
      <Type>Toolbar</Type>
      <Item>
        <Function>Widget</Function>
        <Widget>MapMenu</Widget>
      </Item>
      <Item>
        <Function>Separator</Function>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>Select</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>Pan</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>ZoomInRectangle</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>ZoomInFixed</Widget>
      </Item>
      <Item>
        <Function>Widget</Function>
        <Widget>ZoomOutFixed</Widget>
      </Item>
    </Container>

<!-- MAP -->

    <MapWidget>
      <Name>map</Name>
      <Type>Map</Type>
      <StatusText>The map.</StatusText>
      <Extension>
        <MenuContainer>MapContextMenu</MenuContainer>
      </Extension>
      <MapId>sheboygan</MapId>
    </MapWidget>

<!-- ****************************************** 
* Context Menu - Widgets
*
* Widgets belonging to the map context menu
 ****************************************** -->

<!-- CONTEXT MENU PAN -->

    <Widget>
      <Name>menuPan</Name>
      <Type>Pan</Type>
      <StatusText>Drag the map to view areas out of range.</StatusText>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>pan</ImageClass>
      <Tooltip>Pan mode</Tooltip>
      <Label>Pan</Label>
      <Disabled/>
    </Widget>

<!-- CONTEXT MENU ZOOM RECTANGLE -->

    <Widget>
      <Name>menuZoomInRectangle</Name>
      <Type>Zoom</Type>
      <StatusText>Zoom in on an area.</StatusText>
      <Extension>
        <Tolerance>5</Tolerance>
        <Factor>2</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-in</ImageClass>
      <Tooltip>Zoom In</Tooltip>
      <Label>Zoom Rectangle</Label>
      <Disabled/>
    </Widget>

<!-- CONTEXT MENU ZOOM FIXED (IN) -->

    <Widget>
      <Name>menuZoomInFixed</Name>
      <Type>ZoomOnClick</Type>
      <StatusText>Zoom in by a preset increment.</StatusText>
      <Extension>
        <Factor>2</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-in-fixed</ImageClass>
      <Tooltip>Zoom In</Tooltip>
      <Label>Zoom In</Label>
      <Disabled/>
    </Widget>

<!-- CONTEXT MENU ZOOM FIXED (OUT) -->

    <Widget>
      <Name>menuZoomOutFixed</Name>
      <Type>ZoomOnClick</Type>
      <StatusText>Zoom out by a preset increment</StatusText>
      <Extension>
        <Factor>0.5</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-out-fixed</ImageClass>
      <Tooltip>Zoom Out</Tooltip>
      <Label>Zoom Out</Label>
      <Disabled/>
    </Widget>

<!-- TOOLBAR INITIAL MAP VIEW -->

    <Widget>
      <Name>toolbarInitialMapView</Name>
      <Type>InitialMapView</Type>
      <StatusText>Fit the extents of the map to the window</StatusText>
      <Extension>
        <ViewType>extent</ViewType>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-full</ImageClass>
      <Tooltip>Initial Map View</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

<!-- ****************************************** 
* Panels - Widgets
*
* Widgets belonging to the status bar
 ****************************************** -->

<!-- LEGEND -->

    <Widget>
      <Name>legend</Name>
      <Type>Legend</Type>
      <Extension>
        <ShowRootFolder>false</ShowRootFolder>
      </Extension>
      <StatusText/>
    </Widget>

<!-- SELECTION -->

    <Widget>
      <Name>selectionPanel</Name>
      <Type>SelectionPanel</Type>
      <StatusText/>
    </Widget>

<!-- ****************************************** 
* Misc - Widgets
 ****************************************** -->

<!-- INMAP NAVIGATOR -->

    <Widget>
      <Name>navigator</Name>
      <Type>Navigator</Type>
      <Extension>
      </Extension>
    </Widget>

<!-- ****************************************** 
* Toolbar - Widgets
*
* Widgets belonging to the main toolbar
 ****************************************** -->

<!-- MAPMENU -->

    <Widget>
      <Name>MapMenu</Name>
      <Type>MapMenu</Type>
      <StatusText/>
      <Extension>
        <Folder>Library://Samples/Sheboygan/</Folder>
      </Extension>
      <ImageUrl/>
      <ImageClass/>
      <Tooltip/>
      <Label>Maps</Label>
      <Disabled/>
    </Widget>

<!-- SELECT -->

    <Widget>
      <Name>Select</Name>
      <Type>Select</Type>
      <StatusText>Select features by clicking and dragging.</StatusText>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>select-features</ImageClass>
      <Tooltip>Select mode</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

<!-- PAN -->

    <Widget>
      <Name>Pan</Name>
      <Type>Pan</Type>
      <StatusText>Drag the map to view areas out of range.</StatusText>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>pan</ImageClass>
      <Tooltip>Pan mode</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

<!-- ZOOM IN RECTANGLE -->

    <Widget>
      <Name>ZoomInRectangle</Name>
      <Type>Zoom</Type>
      <StatusText>Zoom in on an area.</StatusText>
      <Extension>
        <Tolerance>5</Tolerance>
        <Factor>2</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-in</ImageClass>
      <Tooltip>Zoom in to a rectangular region.</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

<!-- ZOOM ON CLICK (IN) -->

    <Widget>
      <Name>ZoomInFixed</Name>
      <Type>ZoomOnClick</Type>
      <StatusText>Zoom in by a preset increment.</StatusText>
      <Extension>
        <Factor>4</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-in-fixed</ImageClass>
      <Tooltip>Zoom in by a fixed factor.</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

<!-- ZOOM ON CLICK (OUT) -->

    <Widget>
      <Name>ZoomOutFixed</Name>
      <Type>ZoomOnClick</Type>
      <StatusText>Zoom out by a preset increment</StatusText>
      <Extension>
        <Factor>0.5</Factor>
      </Extension>
      <ImageUrl>images/icons.png</ImageUrl>
      <ImageClass>zoom-out-fixed</ImageClass>
      <Tooltip>Zoom Out by a fixed factor</Tooltip>
      <Label/>
      <Disabled/>
    </Widget>

    <Widget>
      <Name>scalebar</Name>
      <Type>ScalebarDual</Type>
    </Widget>
    
    <Widget>
      <Name>mapTip</Name>
      <Type>Maptip</Type>
      <Extension>
        <Label>Map Tips</Label>
        <Delay>350</Delay>
        <Layer>Parcels</Layer>
      </Extension>
    </Widget>

  </WidgetSet>

  <Extension/>

</ApplicationDefinition>

=== jumpinjackie/mapguide-react-layout/fusion/docs/tutorial/simple/ApplicationDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<ApplicationDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="ApplicationDefinition-1.0.0.xsd">

<!-- ****************************************** 
* MapSet
* 
* Contains the map(s) you want available to your
* application.
 ****************************************** -->

  <MapSet>
    <MapGroup id="sheboygan">
      <Map>
        <Type>MapGuide</Type>
        <SingleTile>true</SingleTile>
        <Extension>
          <ResourceId>Library://Samples/Sheboygan/Maps/Sheboygan.MapDefinition</ResourceId>
        </Extension>
      </Map>
    </MapGroup>
  </MapSet>

<!-- ****************************************** 
* WidgetSet
*
* Contains the widgets you want available to your 
* application.
 ****************************************** -->

  <WidgetSet>

<!-- MAP -->

    <MapWidget>
      <Name>map</Name>
      <Type>Map</Type>
      <MapId>sheboygan</MapId>
    </MapWidget>

<!-- INMAP NAVIGATOR -->

    <Widget>
      <Name>navigator</Name>
      <Type>Navigator</Type>
    </Widget>

    <Widget>
      <Name>pan</Name>
      <Type>Pan</Type>
      <Enabled/>
    </Widget>

  </WidgetSet>

</ApplicationDefinition>
